import '../models/url_models.dart';


List<urlProduct> product = [
  urlProduct(
    buyCounter: 02,
    shopping: 0,
    idUrl: 1,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 15',
    textUrl: 'Samon',
    imageUrl: 'https://www.eatthis.com/wp-content/uploads/sites/4/2023/01/healthy-foods.jpg?quality=82&strip=1',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 2,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 7',
    textUrl: 'Burger',
    imageUrl: 'https://cdn.britannica.com/98/235798-050-3C3BA15D/Hamburger-and-french-fries-paper-box.jpg',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 3,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 9',
    textUrl: 'Chenfood',
    imageUrl: 'https://www.baf.com/wp-content/uploads/2022/06/HB_Lifestyle_Breakfast_Coffee_Bacon_Eggs_Skillet-2-1-1-1-scaled.jpg',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 4,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 8',
    textUrl: 'Hamdai',
    imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/1b/1c/01/bigger-better-breakfast.jpg',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 5,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 12',
    textUrl: 'Susidol',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/pinwheel-sandwiches4-1671200037.jpg?crop=0.9997727789138833xw:1xh;center,top&resize=980:*',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 6,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 18',
    textUrl: 'Bersinpass',
    imageUrl: 'https://media.post.rvohealth.io/wp-content/uploads/sites/2/2020/02/GRT-140628-20_Filling_Foods_That_Actually_Taste_Good-1296x728-header.jpg',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 7,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 10',
    textUrl: 'Turkish',
    imageUrl: 'https://media.cnn.com/api/v1/images/stellar/prod/200402101927-18-best-turkish-foods-lahmacun.jpg?q=w_4000,h_2250,x_0,y_0,c_fill',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 8,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 18',
    textUrl: 'Viram',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/comfort-food-recipes-64668a179574d.png',),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 9,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 6',
    textUrl: 'Taskash',
    imageUrl: 'https://cdn.tasteatlas.com//images/toplistarticles/fc20fbcfe5cd4690ba0cb9614192303a.jpg?w=375&h=280',
  ),
  urlProduct(
    buyCounter: 01,
    shopping: 0,
    idUrl: 10,
    nameShop: 'Chanda foods',
    priceUrl: '\$ 10',
    textUrl: 'Breaksate',
    imageUrl: 'https://media.cnn.com/api/v1/images/stellar/prod/140430115517-06-comfort-foods.jpg?q=x_0,y_0,h_720,w_1280,c_fill/w_800',
  ),
];